import {useEffect,useState} from 'react'
import {getUrlByKey,removeByKey,uploadByKey} from '../utils/charStore'
import PixelSpritePlayer,{DEFAULT_ADJUST,loadSpriteAdjust,spriteAdjustKey,type FrameAdjust} from './PixelSpritePlayer'
import './PixelSpriteSheet.css';import './PixelSpriteSheetUpload.css';import './PixelSpriteCalibrate.css'
export type PixelSheetPose='front'|'side'|'back';export type PixelSheetAction='idle'|'walk'|'mining'
const POSES:{id:PixelSheetPose;label:string}[]=[{id:'front',label:'正面'},{id:'side',label:'側面'},{id:'back',label:'背面'}],ACTIONS:{id:PixelSheetAction;label:string}[]=[{id:'idle',label:'待機'},{id:'walk',label:'走路'},{id:'mining',label:'挖礦'}]
export const spriteSheetKey=(charId:string,pose:PixelSheetPose,action:PixelSheetAction)=>`cb_pixel_sheet_${charId}_${pose}_${action}`
const inspect=(url:string)=>new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error('無法讀取圖片'));image.src=url})
export default function PixelSpriteSheetEditor({charId}:{charId:string}){const[pose,setPose]=useState<PixelSheetPose>('side'),[action,setAction]=useState<PixelSheetAction>('idle'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0),[selected,setSelected]=useState(0),[adjustments,setAdjustments]=useState<FrameAdjust[]>(()=>loadSpriteAdjust(charId,'side','idle'));const fpsKey=`cb_pixel_sheet_fps_${charId}_${action}`,[fps,setFps]=useState(()=>Number(localStorage.getItem(fpsKey))||6),storageKey=spriteSheetKey(charId,pose,action),image=getUrlByKey(storageKey)
useEffect(()=>setFps(Number(localStorage.getItem(`cb_pixel_sheet_fps_${charId}_${action}`))||6),[charId,action]);useEffect(()=>{setAdjustments(loadSpriteAdjust(charId,pose,action));setSelected(0)},[charId,pose,action]);const adjust=(patch:Partial<FrameAdjust>)=>{const next=adjustments.map((item,index)=>index===selected?{...item,...patch}:item);setAdjustments(next);localStorage.setItem(spriteAdjustKey(charId,pose,action),JSON.stringify(next))}
const upload=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setError('');if(file.size>8*1024*1024){setError('圖片超過 8 MB');event.target.value='';return}const reader=new FileReader();setBusy(true);reader.onload=async()=>{try{const url=String(reader.result),size=await inspect(url);if(size.width!==size.height)throw new Error(`圖片必須是正方形，目前為 ${size.width}×${size.height}`);if(size.width%2)throw new Error('圖片寬高必須是偶數');await uploadByKey(storageKey,url);setVersion(value=>value+1)}catch(reason){setError(reason instanceof Error?reason.message:'上傳失敗')}finally{setBusy(false);event.target.value=''}};reader.readAsDataURL(file)}
return <div className="pixel-sheet-editor" data-version={version}><div className="pixel-sheet-tabs"><div>{POSES.map(item=><button key={item.id} className={pose===item.id?'active':''} onClick={()=>setPose(item.id)}>{item.label}</button>)}</div><div>{ACTIONS.map(item=><button key={item.id} className={action===item.id?'active':''} onClick={()=>setAction(item.id)}>{item.label}</button>)}</div></div><div className="pixel-sheet-content"><div><div className="pixel-sheet-preview calibrated">{image?<PixelSpritePlayer src={image} fps={fps} adjustments={adjustments}/>:<span>尚未上傳圖片</span>}<i className="pixel-guide-v"/><i className="pixel-guide-h"/><b>校正後預覽</b></div><div className="pixel-frame-picker">{[0,1,2,3].map(index=><button key={index} className={selected===index?'active':''} onClick={()=>setSelected(index)}>第 {index+1} 格</button>)}</div></div><div className="pixel-sheet-controls"><h4>{POSES.find(item=>item.id===pose)?.label}・{ACTIONS.find(item=>item.id===action)?.label}</h4><p>逐格將角色中心與腳底對齊參考線。</p><label>水平 X <strong>{adjustments[selected]?.x??0}%</strong><input type="range" min="-30" max="30" value={adjustments[selected]?.x??0} onChange={event=>adjust({x:Number(event.target.value)})}/></label><label>垂直 Y <strong>{adjustments[selected]?.y??0}%</strong><input type="range" min="-30" max="30" value={adjustments[selected]?.y??0} onChange={event=>adjust({y:Number(event.target.value)})}/></label><label>縮放 <strong>{adjustments[selected]?.scale??100}%</strong><input type="range" min="70" max="150" value={adjustments[selected]?.scale??100} onChange={event=>adjust({scale:Number(event.target.value)})}/></label><button className="pixel-adjust-reset" onClick={()=>adjust(DEFAULT_ADJUST)}>重設目前影格</button><label>速度 <strong>{fps} FPS</strong><input type="range" min="2" max="12" value={fps} onChange={event=>{const value=Number(event.target.value);setFps(value);localStorage.setItem(fpsKey,String(value))}}/></label><label className="pixel-sheet-upload">{busy?'上傳中…':'上傳 PNG／WebP'}<input type="file" accept="image/png,image/webp" hidden disabled={busy} onChange={upload}/></label>{error&&<em className="pixel-sheet-upload-error">{error}</em>}{image&&<button className="pixel-sheet-remove" onClick={()=>{removeByKey(storageKey);setVersion(value=>value+1)}}>移除動畫</button>}<small>校正值會自動儲存並套用到遊戲。</small></div></div></div>}
